name: smart_feng_shui
description: "Ứng dụng phong thủy toàn diện với nhiều tính năng."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  firebase_messaging: ^14.6.5
  firebase_crashlytics: ^3.3.4
  firebase_analytics: ^10.4.4
  
  # Authentication
  google_sign_in: ^6.1.4
  # Disable facebook_auth temporarily to avoid conflicts
  # flutter_facebook_auth: ^6.0.4
  
  # State Management
  provider: ^6.0.5
  
  # UI Components
  table_calendar: ^3.0.9
  flutter_chat_ui: ^1.6.9
  image_picker: ^1.0.2
  # Sử dụng package khác thay thế carousel_slider
  flutter_carousel_widget: ^2.2.0
  flutter_staggered_grid_view: ^0.7.0
  
  # Storage and Cache
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI/UX
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  lottie: ^2.6.0
  fluttertoast: ^8.2.2
  
  # Utils
  intl: ^0.19.0
  http: ^1.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  connectivity_plus: ^4.0.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/lottie/

  # Example of custom font configuration (uncomment if needed)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
